import numpy as np
a = np.array([[10, 20, 30]])
b = np.array([[40, 50, 60]])
print(a+b)
print(a*b)
print(a+10)
print(b*2)
print("Сумма :", np.sum(a))
print("Среднее значение: ", np.mean(a))
print("Минимальный элемент :", np.min(a))
print("Максимальный элемент :", np.max(a))
print("Отклонение: ", np.std(a))